version: '3'

services:
  traefik:
    image: traefik:v2.8.4
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CF_API_EMAIL=your_email
      - CF_API_KEY=tour_token
      - CF_DNS_API_TOKEN=Kasdasd
      - CF_ZONE_API_TOKEN=asdsad
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/xcliffs/projects/traefik/traefik.yml:/traefik.yml:ro
      - /home/xcliffs/projects/traefik/data/acme.json:/acme.json
      - /home/xcliffs/projects/traefik/data/config.yml:/config.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.your_domain.ru`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=BASIC_AUTH_PASSWORD"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.your_domain.ru`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=your_domain.ru"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.your_domain.ru"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  proxy:
    external: true
